/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.aabu.peaff;

import edu.aabu.peaff.*;
//import edu.aabu.peaff.factory.*;
//import edu.aabu.peaff.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Peparty implements Serializable
{
	/** 
	 * This attribute maps to the column pe_type_code in the peparty table.
	 */
	protected short peTypeCode;

	/** 
	 * This attribute maps to the column pe_main_code in the peparty table.
	 */
	protected short peMainCode;

	/** 
	 * This attribute maps to the column pe_section_code in the peparty table.
	 */
	protected short peSectionCode;

	/** 
	 * This attribute maps to the column pe_class_code in the peparty table.
	 */
	protected short peClassCode;

	/** 
	 * This attribute maps to the column pe_party_desc in the peparty table.
	 */
	protected String pePartyDesc;

	/** 
	 * This attribute maps to the column pe_head_empno in the peparty table.
	 */
	protected short peHeadEmpno;

	/** 
	 * This attribute maps to the column pe_ass_empno in the peparty table.
	 */
	protected short peAssEmpno;

	/** 
	 * This attribute maps to the column post_type in the peparty table.
	 */
	protected short postType;

	/** 
	 * This attribute maps to the column moh_sub_code in the peparty table.
	 */
	protected int mohSubCode;

	/** 
	 * This attribute maps to the column l_party_desc in the peparty table.
	 */
	protected String lPartyDesc;

	/**
	 * Method 'Peparty'
	 * 
	 */
	public Peparty()
	{
	}

	/**
	 * Method 'getPeTypeCode'
	 * 
	 * @return short
	 */
	public short getPeTypeCode()
	{
		return peTypeCode;
	}

	/**
	 * Method 'setPeTypeCode'
	 * 
	 * @param peTypeCode
	 */
	public void setPeTypeCode(short peTypeCode)
	{
		this.peTypeCode = peTypeCode;
	}

	/**
	 * Method 'getPeMainCode'
	 * 
	 * @return short
	 */
	public short getPeMainCode()
	{
		return peMainCode;
	}

	/**
	 * Method 'setPeMainCode'
	 * 
	 * @param peMainCode
	 */
	public void setPeMainCode(short peMainCode)
	{
		this.peMainCode = peMainCode;
	}

	/**
	 * Method 'getPeSectionCode'
	 * 
	 * @return short
	 */
	public short getPeSectionCode()
	{
		return peSectionCode;
	}

	/**
	 * Method 'setPeSectionCode'
	 * 
	 * @param peSectionCode
	 */
	public void setPeSectionCode(short peSectionCode)
	{
		this.peSectionCode = peSectionCode;
	}

	/**
	 * Method 'getPeClassCode'
	 * 
	 * @return short
	 */
	public short getPeClassCode()
	{
		return peClassCode;
	}

	/**
	 * Method 'setPeClassCode'
	 * 
	 * @param peClassCode
	 */
	public void setPeClassCode(short peClassCode)
	{
		this.peClassCode = peClassCode;
	}

	/**
	 * Method 'getPePartyDesc'
	 * 
	 * @return String
	 */
	public String getPePartyDesc()
	{
		return pePartyDesc;
	}

	/**
	 * Method 'setPePartyDesc'
	 * 
	 * @param pePartyDesc
	 */
	public void setPePartyDesc(String pePartyDesc)
	{
		this.pePartyDesc = pePartyDesc;
	}

	/**
	 * Method 'getPeHeadEmpno'
	 * 
	 * @return short
	 */
	public short getPeHeadEmpno()
	{
		return peHeadEmpno;
	}

	/**
	 * Method 'setPeHeadEmpno'
	 * 
	 * @param peHeadEmpno
	 */
	public void setPeHeadEmpno(short peHeadEmpno)
	{
		this.peHeadEmpno = peHeadEmpno;
	}

	/**
	 * Method 'getPeAssEmpno'
	 * 
	 * @return short
	 */
	public short getPeAssEmpno()
	{
		return peAssEmpno;
	}

	/**
	 * Method 'setPeAssEmpno'
	 * 
	 * @param peAssEmpno
	 */
	public void setPeAssEmpno(short peAssEmpno)
	{
		this.peAssEmpno = peAssEmpno;
	}

	/**
	 * Method 'getPostType'
	 * 
	 * @return short
	 */
	public short getPostType()
	{
		return postType;
	}

	/**
	 * Method 'setPostType'
	 * 
	 * @param postType
	 */
	public void setPostType(short postType)
	{
		this.postType = postType;
	}

	/**
	 * Method 'getMohSubCode'
	 * 
	 * @return int
	 */
	public int getMohSubCode()
	{
		return mohSubCode;
	}

	/**
	 * Method 'setMohSubCode'
	 * 
	 * @param mohSubCode
	 */
	public void setMohSubCode(int mohSubCode)
	{
		this.mohSubCode = mohSubCode;
	}

	/**
	 * Method 'getLPartyDesc'
	 * 
	 * @return String
	 */
	public String getLPartyDesc()
	{
		return lPartyDesc;
	}

	/**
	 * Method 'setLPartyDesc'
	 * 
	 * @param lPartyDesc
	 */
	public void setLPartyDesc(String lPartyDesc)
	{
		this.lPartyDesc = lPartyDesc;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Peparty)) {
			return false;
		}
		
		final Peparty _cast = (Peparty) _other;
		if (peTypeCode != _cast.peTypeCode) {
			return false;
		}
		
		if (peMainCode != _cast.peMainCode) {
			return false;
		}
		
		if (peSectionCode != _cast.peSectionCode) {
			return false;
		}
		
		if (peClassCode != _cast.peClassCode) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) peTypeCode;
		_hashCode = 29 * _hashCode + (int) peMainCode;
		_hashCode = 29 * _hashCode + (int) peSectionCode;
		_hashCode = 29 * _hashCode + (int) peClassCode;
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return PepartyPk
	 */
	public PepartyPk createPk()
	{
		return new PepartyPk(peTypeCode, peMainCode, peSectionCode, peClassCode);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.aabu.peaff.dto.Peparty: " );
		ret.append( "peTypeCode=" + peTypeCode );
		ret.append( ", peMainCode=" + peMainCode );
		ret.append( ", peSectionCode=" + peSectionCode );
		ret.append( ", peClassCode=" + peClassCode );
		ret.append( ", pePartyDesc=" + pePartyDesc );
		ret.append( ", peHeadEmpno=" + peHeadEmpno );
		ret.append( ", peAssEmpno=" + peAssEmpno );
		ret.append( ", postType=" + postType );
		ret.append( ", mohSubCode=" + mohSubCode );
		ret.append( ", lPartyDesc=" + lPartyDesc );
		return ret.toString();
	}

}
