/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.aabu.maintenence.dto;

import edu.aabu.maintenence.dao.*;
import edu.aabu.maintenence.factory.*;
import edu.aabu.maintenence.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class MaintenanceOrdersActions implements Serializable
{
	/** 
	 * This attribute maps to the column ACTION_DESC in the MAINTENANCE_ORDERS_ACTIONS table.
	 */
	protected String actionDesc;

	/** 
	 * This attribute maps to the column ACTION_TIME in the MAINTENANCE_ORDERS_ACTIONS table.
	 */
	protected Date actionTime;

	/** 
	 * This attribute maps to the column ORDER_NO in the MAINTENANCE_ORDERS_ACTIONS table.
	 */
	protected int orderNo;

	/** 
	 * This attribute maps to the column ORDER_YEAR in the MAINTENANCE_ORDERS_ACTIONS table.
	 */
	protected short orderYear;

	/**
	 * Method 'MaintenanceOrdersActions'
	 * 
	 */
	public MaintenanceOrdersActions()
	{
	}

	/**
	 * Method 'getActionDesc'
	 * 
	 * @return String
	 */
	public String getActionDesc()
	{
		return actionDesc;
	}

	/**
	 * Method 'setActionDesc'
	 * 
	 * @param actionDesc
	 */
	public void setActionDesc(String actionDesc)
	{
		this.actionDesc = actionDesc;
	}

	/**
	 * Method 'getActionTime'
	 * 
	 * @return Date
	 */
	public Date getActionTime()
	{
		return actionTime;
	}

	/**
	 * Method 'setActionTime'
	 * 
	 * @param actionTime
	 */
	public void setActionTime(Date actionTime)
	{
		this.actionTime = actionTime;
	}

	/**
	 * Method 'getOrderNo'
	 * 
	 * @return int
	 */
	public int getOrderNo()
	{
		return orderNo;
	}

	/**
	 * Method 'setOrderNo'
	 * 
	 * @param orderNo
	 */
	public void setOrderNo(int orderNo)
	{
		this.orderNo = orderNo;
	}

	/**
	 * Method 'getOrderYear'
	 * 
	 * @return short
	 */
	public short getOrderYear()
	{
		return orderYear;
	}

	/**
	 * Method 'setOrderYear'
	 * 
	 * @param orderYear
	 */
	public void setOrderYear(short orderYear)
	{
		this.orderYear = orderYear;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof MaintenanceOrdersActions)) {
			return false;
		}
		
		final MaintenanceOrdersActions _cast = (MaintenanceOrdersActions) _other;
		if (actionDesc == null ? _cast.actionDesc != actionDesc : !actionDesc.equals( _cast.actionDesc )) {
			return false;
		}
		
		if (actionTime == null ? _cast.actionTime != actionTime : !actionTime.equals( _cast.actionTime )) {
			return false;
		}
		
		if (orderNo != _cast.orderNo) {
			return false;
		}
		
		if (orderYear != _cast.orderYear) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (actionDesc != null) {
			_hashCode = 29 * _hashCode + actionDesc.hashCode();
		}
		
		if (actionTime != null) {
			_hashCode = 29 * _hashCode + actionTime.hashCode();
		}
		
		_hashCode = 29 * _hashCode + orderNo;
		_hashCode = 29 * _hashCode + (int) orderYear;
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return MaintenanceOrdersActionsPk
	 */
	public MaintenanceOrdersActionsPk createPk()
	{
		return new MaintenanceOrdersActionsPk(orderNo, orderYear, actionTime);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.aabu.maintenence.dto.MaintenanceOrdersActions: " );
		ret.append( "actionDesc=" + actionDesc );
		ret.append( ", actionTime=" + actionTime );
		ret.append( ", orderNo=" + orderNo );
		ret.append( ", orderYear=" + orderYear );
		return ret.toString();
	}

}
