/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.aabu.maintenence.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the MAINTENANCE_ORDERS_ACTIONS table.
 */
public class MaintenanceOrdersActionsPk implements Serializable
{
	protected int orderNo;

	protected short orderYear;

	protected Date actionTime;

	/** 
	 * This attribute represents whether the primitive attribute orderNo is null.
	 */
	protected boolean orderNoNull;

	/** 
	 * This attribute represents whether the primitive attribute orderYear is null.
	 */
	protected boolean orderYearNull;

	/** 
	 * Sets the value of orderNo
	 */
	public void setOrderNo(int orderNo)
	{
		this.orderNo = orderNo;
	}

	/** 
	 * Gets the value of orderNo
	 */
	public int getOrderNo()
	{
		return orderNo;
	}

	/** 
	 * Sets the value of orderYear
	 */
	public void setOrderYear(short orderYear)
	{
		this.orderYear = orderYear;
	}

	/** 
	 * Gets the value of orderYear
	 */
	public short getOrderYear()
	{
		return orderYear;
	}

	/** 
	 * Sets the value of actionTime
	 */
	public void setActionTime(Date actionTime)
	{
		this.actionTime = actionTime;
	}

	/** 
	 * Gets the value of actionTime
	 */
	public Date getActionTime()
	{
		return actionTime;
	}

	/**
	 * Method 'MaintenanceOrdersActionsPk'
	 * 
	 */
	public MaintenanceOrdersActionsPk()
	{
	}

	/**
	 * Method 'MaintenanceOrdersActionsPk'
	 * 
	 * @param orderNo
	 * @param orderYear
	 * @param actionTime
	 */
	public MaintenanceOrdersActionsPk(final int orderNo, final short orderYear, final Date actionTime)
	{
		this.orderNo = orderNo;
		this.orderYear = orderYear;
		this.actionTime = actionTime;
	}

	/** 
	 * Sets the value of orderNoNull
	 */
	public void setOrderNoNull(boolean orderNoNull)
	{
		this.orderNoNull = orderNoNull;
	}

	/** 
	 * Gets the value of orderNoNull
	 */
	public boolean isOrderNoNull()
	{
		return orderNoNull;
	}

	/** 
	 * Sets the value of orderYearNull
	 */
	public void setOrderYearNull(boolean orderYearNull)
	{
		this.orderYearNull = orderYearNull;
	}

	/** 
	 * Gets the value of orderYearNull
	 */
	public boolean isOrderYearNull()
	{
		return orderYearNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof MaintenanceOrdersActionsPk)) {
			return false;
		}
		
		final MaintenanceOrdersActionsPk _cast = (MaintenanceOrdersActionsPk) _other;
		if (orderNo != _cast.orderNo) {
			return false;
		}
		
		if (orderYear != _cast.orderYear) {
			return false;
		}
		
		if (actionTime == null ? _cast.actionTime != actionTime : !actionTime.equals( _cast.actionTime )) {
			return false;
		}
		
		if (orderNoNull != _cast.orderNoNull) {
			return false;
		}
		
		if (orderYearNull != _cast.orderYearNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + orderNo;
		_hashCode = 29 * _hashCode + (int) orderYear;
		if (actionTime != null) {
			_hashCode = 29 * _hashCode + actionTime.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (orderNoNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (orderYearNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.aabu.maintenence.dto.MaintenanceOrdersActionsPk: " );
		ret.append( "orderNo=" + orderNo );
		ret.append( ", orderYear=" + orderYear );
		ret.append( ", actionTime=" + actionTime );
		return ret.toString();
	}

}
