/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */
package edu.aabu.maintenence.dto;

import java.io.Serializable;
import java.util.Date;

public class MaintenanceOrders implements Serializable {

    /**
     * This attribute maps to the column order_no in the maintenance_orders table.
     */
    protected int orderNo;
    /**
     * This attribute maps to the column order_year in the maintenance_orders table.
     */
    protected short orderYear;
    /**
     * This attribute maps to the column pe_emp_no in the maintenance_orders table.
     */
    protected int peEmpNo;
    /**
     * This attribute maps to the column order_date in the maintenance_orders table.
     */
    protected Date orderDate;
    /**
     * This attribute maps to the column problem_desc in the maintenance_orders table.
     */
    protected String problemDesc;
    /**
     * This attribute maps to the column pe_type_code in the maintenance_orders table.
     */
    protected short peTypeCode;
    /**
     * This attribute maps to the column pe_main_code in the maintenance_orders table.
     */
    protected short peMainCode;
    /**
     * This attribute maps to the column pe_section_code in the maintenance_orders table.
     */
    protected short peSectionCode;
    /**
     * This attribute maps to the column pe_class_code in the maintenance_orders table.
     */
    protected short peClassCode;
    /**
     * This attribute maps to the column emp_phone in the maintenance_orders table.
     */
    protected String empPhone;
    /**
     * This attribute maps to the column emp_opinion in the maintenance_orders table.
     */
    protected String empOpinion;
    /**
     * This attribute maps to the column order_emerg in the maintenance_orders table.
     */
    protected short orderEmerg;
    /**
     * This attribute maps to the column order_status in the maintenance_orders table.
     */
    protected short orderStatus;
    /**
     * This attribute maps to the column order_no in the maintenance_orders table.
     */
    private String address;
    private int managerId;
    // modyfied by akaleek to support more than department
    /**
     * This attribute maps to the column to_pe_type_code in the maintenance_orders table.
     */
    private short toPeTypeCode;
    /**
     * This attribute maps to the column to_pe_main_code in the maintenance_orders table.
     */
    private short toPeMainCode;
    /**
     * This attribute maps to the column to_pe_section_code in the maintenance_orders table.
     */
    private short toPeSectionCode;
    /**
     * This attribute maps to the column to_pe_class_code in the maintenance_orders table.
     */
    private short toPeClassCode;
    /**
     * This attribute maps to the column close_reason in the maintenance_orders table.
     */
    private String closeReason;
    
    //-- end-------
    /**
     * Method 'MaintenanceOrders'
     *
     */
    public MaintenanceOrders() {
        orderDate = new Date();
        empPhone = "";
        empOpinion = "";
        problemDesc = "";
    }

    /**
     * Method 'getOrderNo'
     *
     * @return int
     */
    public int getOrderNo() {
        return orderNo;
    }

    /**
     * Method 'setOrderNo'
     *
     * @param orderNo
     */
    public void setOrderNo(int orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * Method 'getOrderYear'
     *
     * @return short
     */
    public short getOrderYear() {
        return orderYear;
    }

    /**
     * Method 'setOrderYear'
     *
     * @param orderYear
     */
    public void setOrderYear(short orderYear) {
        this.orderYear = orderYear;
    }

    /**
     * Method 'getPeEmpNo'
     *
     * @return int
     */
    public int getPeEmpNo() {
        return peEmpNo;
    }

    /**
     * Method 'setPeEmpNo'
     *
     * @param peEmpNo
     */
    public void setPeEmpNo(int peEmpNo) {
        this.peEmpNo = peEmpNo;
    }

    /**
     * Method 'getOrderDate'
     *
     * @return Date
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * Method 'setOrderDate'
     *
     * @param orderDate
     */
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * Method 'getProblemDesc'
     *
     * @return String
     */
    public String getProblemDesc() {
        return problemDesc;
    }

    /**
     * Method 'setProblemDesc'
     *
     * @param problemDesc
     */
    public void setProblemDesc(String problemDesc) {
        this.problemDesc = problemDesc;
    }

    /**
     * Method 'getPeTypeCode'
     *
     * @return short
     */
    public short getPeTypeCode() {
        return peTypeCode;
    }

    /**
     * Method 'setPeTypeCode'
     *
     * @param peTypeCode
     */
    public void setPeTypeCode(short peTypeCode) {
        this.peTypeCode = peTypeCode;
    }

    /**
     * Method 'getPeMainCode'
     *
     * @return short
     */
    public short getPeMainCode() {
        return peMainCode;
    }

    /**
     * Method 'setPeMainCode'
     *
     * @param peMainCode
     */
    public void setPeMainCode(short peMainCode) {
        this.peMainCode = peMainCode;
    }

    /**
     * Method 'getPeSectionCode'
     *
     * @return short
     */
    public short getPeSectionCode() {
        return peSectionCode;
    }

    /**
     * Method 'setPeSectionCode'
     *
     * @param peSectionCode
     */
    public void setPeSectionCode(short peSectionCode) {
        this.peSectionCode = peSectionCode;
    }

    /**
     * Method 'getPeClassCode'
     *
     * @return short
     */
    public short getPeClassCode() {
        return peClassCode;
    }

    /**
     * Method 'setPeClassCode'
     *
     * @param peClassCode
     */
    public void setPeClassCode(short peClassCode) {
        this.peClassCode = peClassCode;
    }

    /**
     * Method 'getEmpPhone'
     *
     * @return String
     */
    public String getEmpPhone() {
        return empPhone;
    }

    /**
     * Method 'setEmpPhone'
     *
     * @param empPhone
     */
    public void setEmpPhone(String empPhone) {
        this.empPhone = empPhone;
    }

    /**
     * Method 'getEmpOpinion'
     *
     * @return String
     */
    public String getEmpOpinion() {
        return empOpinion;
    }

    /**
     * Method 'setEmpOpinion'
     *
     * @param empOpinion
     */
    public void setEmpOpinion(String empOpinion) {
        this.empOpinion = empOpinion;
    }

    /**
     * Method 'getOrderEmerg'
     *
     * @return short
     */
    public short getOrderEmerg() {
        return orderEmerg;
    }

    /**
     * Method 'setOrderEmerg'
     *
     * @param orderEmerg
     */
    public void setOrderEmerg(short orderEmerg) {
        this.orderEmerg = orderEmerg;
    }

    /**
     * Method 'getOrderStatus'
     *
     * @return short
     */
    public short getOrderStatus() {
        return orderStatus;
    }

    /**
     * Method 'setOrderStatus'
     *
     * @param orderStatus
     */
    public void setOrderStatus(short orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * Method 'equals'
     *
     * @param _other
     * @return boolean
     */
    public boolean equals(Object _other) {
        if (_other == null) {
            return false;
        }

        if (_other == this) {
            return true;
        }

        if (!(_other instanceof MaintenanceOrders)) {
            return false;
        }

        final MaintenanceOrders _cast = (MaintenanceOrders) _other;
        if (orderNo != _cast.orderNo) {
            return false;
        }

        if (orderYear != _cast.orderYear) {
            return false;
        }

        if (peEmpNo != _cast.peEmpNo) {
            return false;
        }

        if (orderDate == null ? _cast.orderDate != orderDate : !orderDate.equals(_cast.orderDate)) {
            return false;
        }

        if (problemDesc == null ? _cast.problemDesc != problemDesc : !problemDesc.equals(_cast.problemDesc)) {
            return false;
        }

        if (peTypeCode != _cast.peTypeCode) {
            return false;
        }

        if (peMainCode != _cast.peMainCode) {
            return false;
        }

        if (peSectionCode != _cast.peSectionCode) {
            return false;
        }

        if (peClassCode != _cast.peClassCode) {
            return false;
        }

        if (empPhone == null ? _cast.empPhone != empPhone : !empPhone.equals(_cast.empPhone)) {
            return false;
        }

        if (empOpinion == null ? _cast.empOpinion != empOpinion : !empOpinion.equals(_cast.empOpinion)) {
            return false;
        }

        if (orderEmerg != _cast.orderEmerg) {
            return false;
        }

        if (orderStatus != _cast.orderStatus) {
            return false;
        }

        return true;
    }

    /**
     * Method 'hashCode'
     *
     * @return int
     */
    public int hashCode() {
        int _hashCode = 0;
        _hashCode = 29 * _hashCode + orderNo;
        _hashCode = 29 * _hashCode + (int) orderYear;
        _hashCode = 29 * _hashCode + peEmpNo;
        if (orderDate != null) {
            _hashCode = 29 * _hashCode + orderDate.hashCode();
        }

        if (problemDesc != null) {
            _hashCode = 29 * _hashCode + problemDesc.hashCode();
        }

        _hashCode = 29 * _hashCode + (int) peTypeCode;
        _hashCode = 29 * _hashCode + (int) peMainCode;
        _hashCode = 29 * _hashCode + (int) peSectionCode;
        _hashCode = 29 * _hashCode + (int) peClassCode;
        if (empPhone != null) {
            _hashCode = 29 * _hashCode + empPhone.hashCode();
        }

        if (empOpinion != null) {
            _hashCode = 29 * _hashCode + empOpinion.hashCode();
        }

        _hashCode = 29 * _hashCode + (int) orderEmerg;
        _hashCode = 29 * _hashCode + (int) orderStatus;
        return _hashCode;
    }

    /**
     * Method 'toString'
     *
     * @return String
     */
    public String toString() {
        StringBuffer ret = new StringBuffer();
        ret.append("edu.aabu.maintenence.dto.MaintenanceOrders: ");
        ret.append("orderNo=" + orderNo);
        ret.append(", orderYear=" + orderYear);
        ret.append(", peEmpNo=" + peEmpNo);
        ret.append(", orderDate=" + orderDate);
        ret.append(", problemDesc=" + problemDesc);
        ret.append(", peTypeCode=" + peTypeCode);
        ret.append(", peMainCode=" + peMainCode);
        ret.append(", peSectionCode=" + peSectionCode);
        ret.append(", peClassCode=" + peClassCode);
        ret.append(", empPhone=" + empPhone);
        ret.append(", empOpinion=" + empOpinion);
        ret.append(", orderEmerg=" + orderEmerg);
        ret.append(", orderStatus=" + orderStatus);
        ret.append(", peToTypeCode=" + toPeTypeCode);
        ret.append(", peToMainCode=" + toPeMainCode);
        ret.append(", peToSectionCode=" + toPeSectionCode);
        ret.append(", peToClassCode=" + toPeClassCode);
        return ret.toString();
    }

    /**
     * @return the address
     */
    public String getAddress() {
        return address;
    }

    /**
     * @param address the address to set
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * @return the managerId
     */
    public int getManagerId() {
        return managerId;
    }

    /**
     * @param managerId the managerId to set
     */
    public void setManagerId(int managerId) {
        this.managerId = managerId;
    }

    /**
     * @return the toPeTypeCode
     */
    public short getToPeTypeCode() {
        return toPeTypeCode;
    }

    /**
     * @param toPeTypeCode the toPeTypeCode to set
     */
    public void setToPeTypeCode(short toPeTypeCode) {
        this.toPeTypeCode = toPeTypeCode;
    }

    /**
     * @return the toPeMainCode
     */
    public short getToPeMainCode() {
        return toPeMainCode;
    }

    /**
     * @param toPeMainCode the toPeMainCode to set
     */
    public void setToPeMainCode(short toPeMainCode) {
        this.toPeMainCode = toPeMainCode;
    }

    /**
     * @return the toPeSectionCode
     */
    public short getToPeSectionCode() {
        return toPeSectionCode;
    }

    /**
     * @param toPeSectionCode the toPeSectionCode to set
     */
    public void setToPeSectionCode(short toPeSectionCode) {
        this.toPeSectionCode = toPeSectionCode;
    }

    /**
     * @return the toPeClassCode
     */
    public short getToPeClassCode() {
        return toPeClassCode;
    }

    /**
     * @param toPeClassCode the toPeClassCode to set
     */
    public void setToPeClassCode(short toPeClassCode) {
        this.toPeClassCode = toPeClassCode;
    }

    /**
     * @return the closeReason
     */
    public String getCloseReason() {
        return closeReason;
    }

    /**
     * @param closeReason the closeReason to set
     */
    public void setCloseReason(String closeReason) {
        this.closeReason = closeReason;
    }
}
